name: ${project.artifactId}
main: com.titongames.titonguest.Main
authors: [SkuLL]
version: ${project.version}
website: ${project.url}
description: ${project.description}

commands:
    titonguest:
        description: Shows TitonGuest help.
        usage: /<command>
        permissions-message: You don't have permission to use this command.
    ttp:
        description: TitonTeleport.
        usage: /<command>
        permissions-message: You don't have permission to use this command.
    list:
        description: Shows the player list.
        usage: /<command>
        permissions-message: You don't have permission to use this command.
    players:
        description: Shows the player list.
        usage: /<command>
        permissions-message: You don't have permission to use this command.
    who:
        description: Shows the player list.
        usage: /<command>
        permissions-message: You don't have permission to use this command.
    warp:
        description: Warp a player to a location.
        usage: /<command> <warpname>
        permissions-message: You don't have permission to use this command.
    warplist:
        description: Lists all available warps.
        usage: /<command>
        permissions-message: You don't have permission to use this command.
    setwarp:
        description: Creates a warp.
        usage: /<command> <warpname>
        permissions-message: You don't have permission to use this command.
    delwarp:
        description: Deletes a warp.
        usage: /<command> <warpname>
        permissions-message: You don't have permission to use this command.